version: '3.5'
services:
  redis_user_test:
    container_name: app-redis-test
    image: sickp/alpine-redis:3.2.2
    ports:
      - "6379:6379"
    networks:
      - proxynet
#  redis_user:
#    container_name: app-redis
#    image: sickp/alpine-redis:3.2.2
#    ports:
#      - "6379:6379"
#    networks:
#      - proxynet

#  elasticsearch:
#    image: elasticsearch:6.5.0
#    container_name: app-elasticsearch
#    ports:
#      - "9200:9200"
#    networks:
#      - proxynet

  elasticsearch_test:
    image: elasticsearch:6.5.0
    container_name: app-elasticsearch-test
    ports:
      - "9200:9200"
    networks:
      - proxynet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: app-kibana
    ports:
      - "5601:5601"
    networks:
      - proxynet

  database:
    image: mariadb:10.3
    container_name: app-database
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=appdb"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=123"
      - "MYSQL_ROOT_PASSWORD=123"
    ports:
      - "3306:3306"
    networks:
      - proxynet

networks:
  proxynet:
    name: db_network