version: '3.5'
services:
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        container_name: user-api-php
        volumes:
          - ./:/var/www
        environment:
          - "DB_PORT=3306"
          - "DB_HOST=database"
        networks:
          - db-net
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        container_name: user-api-web
        volumes:
          - app
        ports:
          - 8000:8000
        networks:
          - db-net

networks:
  db-net:
    external:
      name: db_network
